version: "3.7"
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      demo_net:
        ipv4_address: 172.28.1.1
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports: 
    - 3306:3306

  adminer:
    image: adminer
    restart: always
    networks:
      demo_net:
        ipv4_address: 172.28.1.2
    ports:
    - 8080:8080

  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    networks:
      demo_net:
        ipv4_address: 172.28.1.3
    expose:
      - "63791"
    ports:
      - "63791:6379"
  
  replica:
    build:
      context: .
      dockerfile: Dockerfile-redis
    networks:
      demo_net:
        ipv4_address: 172.28.1.4
    expose:
      - "6379"
    ports:
      - "63790:6379"

  service:
    build:
      context: .
      dockerfile: Dockerfile-service
    networks:
      demo_net:
        ipv4_address: 172.28.1.5
    environment:
      - DB=${DB}
      - HOST=${HOST}
      - PASS=${PASS}
      - USER=${USER}
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_READER_HOST=${REDIS_READER_HOST}
      - REDIS_MASTER_PORT=${REDIS_MASTER_PORT}
      - REDIS_READER_PORT=${REDIS_READER_PORT}
      - SQL_QUERY_TEXT=${SQL_QUERY_TEXT}
      - FLASK_ENV=${FLASK_ENV}
      - PYTHONPATH=${PYTHONPATH}
    expose: 
      - 80
    ports:
      - 80:80

networks:
  demo_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16